import { CardType, CardCategory, CardPropsBase } from './components/Card'

/*
 * TODO: Add new cards:
*/
/*
 * TODO: Add new cards:
*/

export const CardDefinitions: CardPropsBase[] = [
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'puzzled',
    definition: 'Unable to understand; perplexed.',
    source: 'https://www.lexico.com/en/definition/puzzled',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'angry',
    definition: 'Feeling or showing strong annoyance, displeasure, or hostility; full of anger.',
    source: 'https://www.lexico.com/en/definition/angry',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'happy',
    definition: 'Having a sense of confidence in or satisfaction with (a person, arrangement, or situation).',
    source: 'https://www.lexico.com/en/definition/happy',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'sad',
    definition: 'Feeling or showing sorrow; unhappy.',
    source: 'https://www.lexico.com/en/definition/sad',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'scared',
    definition: 'Fearful; frightened.',
    source: 'https://www.lexico.com/en/definition/scared',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'cold',
    definition: 'Lacking affection or warmth of feeling; unemotional.',
    source: 'https://www.lexico.com/en/definition/cold',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'compersion',
    definition: 'Compersion is an empathetic state of happiness and joy experienced when another individual experiences happiness and joy.',
    source: 'https://www.definitions.net/definition/compersion',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'confused',
    definition: 'Unable to think clearly; bewildered.',
    source: 'https://www.lexico.com/en/definition/confused',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'embarrassed',
    definition: 'Feeling or showing embarrassment.',
    source: 'https://www.lexico.com/en/definition/embarrassed',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'jealous',
    definition: 'Feeling or showing envy of someone or their achievements and advantages.',
    source: 'https://www.lexico.com/en/definition/jealous',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'lonely',
    definition: 'Affected with, characterized by, or causing a depressing feeling of being alone; lonesome.',
    source: 'https://www.dictionary.com/browse/affected',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'tired',
    definition: 'Drained of strength and energy; fatigued often to the point of exhaustion.',
    source: 'https://www.merriam-webster.com/dictionary/tired',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'affectionate',
    definition: 'Readily feeling or showing fondness or tenderness.',
    source: 'https://www.lexico.com/en/definition/affectionate',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'anxious',
    definition: 'Experiencing worry, unease, or nervousness, typically about an imminent event or something with an uncertain outcome.',
    source: 'https://www.lexico.com/en/definition/anxious',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'empowered',
    definition: 'Having been given the power to make choices relevant to one\'s situation.',
    source: 'https://en.wiktionary.org/wiki/empowered',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'encouraged',
    definition: 'To stimulate by assistance, approval, etc.',
    source: 'https://www.dictionary.com/browse/encouraged',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'excited',
    definition: 'Very enthusiastic and eager.',
    source: 'https://www.lexico.com/en/definition/excited',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'frustrated',
    definition: 'Prevented from progressing, succeeding, or being fulfilled.',
    source: 'https://www.lexico.com/en/definition/frustrated',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'hurt',
    definition: 'To feel or suffer bodily or mental pain or distress.',
    source: 'https://www.dictionary.com/browse/hurt',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'hopeless',
    definition: 'Having no expectation of good or success.',
    source: 'https://www.merriam-webster.com/dictionary/hopeless',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'irritable',
    definition: 'Easily exasperated or excited.',
    source: 'https://en.wiktionary.org/wiki/irritable',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'overwhelmed',
    definition: 'Completely overcome in mind or feeling.',
    source: 'https://www.dictionary.com/browse/overwhelmed',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'annoyed',
    definition: 'Feeling or showing angry irritation.',
    source: 'https://www.merriam-webster.com/dictionary/annoyed',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'centered',
    definition: 'Emotionally stable and secure.',
    source: 'https://www.merriam-webster.com/dictionary/centered',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'depressed',
    definition: 'Low in spirits.',
    source: 'https://www.merriam-webster.com/dictionary/depressed',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'disappointed',
    definition: 'Depressed or discouraged by the failure of one\'s hopes or expectations.',
    source: 'https://www.dictionary.com/browse/disappointed',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'discouraged',
    definition: 'Having lost confidence or enthusiasm; disheartened.',
    source: 'https://www.lexico.com/en/definition/discouraged',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'engaged',
    definition: 'Involved in an activity.',
    source: 'https://www.merriam-webster.com/dictionary/engaged',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'fidgety',
    definition: 'Inclined to fidget; restless or uneasy.',
    source: 'https://www.lexico.com/en/definition/fidgety',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'fulfilled',
    definition: 'Satisfied or happy because of fully developing one\'s abilities or character.',
    source: 'https://www.lexico.com/en/definition/fulfilled',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'grateful',
    definition: 'Warmly or deeply appreciative of kindness or benefits received; thankful.',
    source: 'https://www.dictionary.com/browse/grateful',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'impatient',
    definition: 'Restless in desire or expectation; eagerly desirous.',
    source: 'https://www.dictionary.com/browse/impatient',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'insecure',
    definition: 'Not confident or certain; uneasy; anxious.',
    source: 'https://www.dictionary.com/browse/insecure',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'inspired',
    definition: 'Aroused, animated, or imbued with the spirit to do something.',
    source: 'https://www.dictionary.com/browse/inspired',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'joyful',
    definition: 'Feeling, expressing, or causing great pleasure and happiness.',
    source: 'https://www.lexico.com/en/definition/joyful',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'peaceful',
    definition: 'Free from disturbance; tranquil.',
    source: 'https://www.lexico.com/en/definition/peaceful',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'secure',
    definition: 'Fixed or fastened so as not to give way, become loose, or be lost.',
    source: 'https://www.lexico.com/en/definition/secure',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'startled',
    definition: 'Feeling or showing sudden shock or alarm.',
    source: 'https://www.lexico.com/en/definition/startled',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'uncomfortable',
    definition: 'Causing or feeling slight pain or physical discomfort.',
    source: 'https://www.lexico.com/en/definition/uncomfortable',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'upset',
    definition: 'Unhappy, disappointed, or worried.',
    source: 'https://www.lexico.com/en/definition/upset',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'vulnerable',
    definition: 'More or most likely to be exposed to the chance of being attacked or harmed, either physically or emotionally.',
    source: 'https://en.wiktionary.org/wiki/vulnerable',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'hopeful',
    definition: 'Promising advantage or success.',
    source: 'https://www.dictionary.com/browse/hopeful',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'defensive',
    definition: 'Very anxious to challenge or avoid criticism.',
    source: 'https://www.encyclopedia.com/literature-and-arts/language-linguistics-and-literary-terms/english-vocabulary-d/defensive',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'energetic',
    definition: 'Possessing or exerting or displaying energy.',
    source: 'https://www.vocabulary.com/dictionary/energetic',
  },
  {
    type: CardType.Feeling,
    category: CardCategory.Meow,
    name: 'friendly',
    definition: 'Outgoing and pleasant in social relations.',
    source: 'https://www.thefreedictionary.com/friendly',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'empathy',
    definition: 'The ability to understand and share the feelings (and needs) of another.',
    source: 'https://www.lexico.com/en/definition/empathy',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'connection',
    definition: 'A feeling of understanding and ease of communication between two or more people.',
    source: 'https://en.wiktionary.org/wiki/connection',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'harmony',
    definition: 'A consistent, orderly, or pleasing arrangement of parts; congruity.',
    source: 'https://www.dictionary.com/browse/harmony',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'reassurance',
    definition: 'The action of removing someone\'s doubts or fears.',
    source: 'https://www.lexico.com/en/definition/reassurance',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'support',
    definition: 'To verify; to make good; to substantiate; to establish; to sustain.',
    source: 'https://en.wiktionary.org/wiki/support',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'appreciation',
    definition: 'Recognition and enjoyment of the good qualities of someone or something.',
    source: 'https://www.lexico.com/en/definition/appreciation',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'autonomy',
    definition: 'The capacity to make an informed, uncoerced decision.',
    source: 'https://en.wiktionary.org/wiki/autonomy',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'celebration',
    definition: 'The act, process of showing appreciation, gratitude and/or remembrance, notably as a social event.',
    source: 'https://en.wiktionary.org/wiki/celebration',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'honesty',
    definition: 'Fairness and straightforwardness of conduct.',
    source: 'https://www.merriam-webster.com/dictionary/honesty',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'space',
    definition: 'The quality or state of being apart from company or observation.',
    source: 'https://www.merriam-webster.com/dictionary/privacy',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'advice',
    definition: 'An opinion or recommendation offered as a guide to action, conduct, etc.',
    source: 'https://www.dictionary.com/browse/advice',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'affection',
    definition: 'A feeling of liking and caring for someone or something.',
    source: 'https://www.merriam-webster.com/dictionary/affection',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'care',
    definition: 'The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something.',
    source: 'https://www.lexico.com/en/definition/care',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'community',
    definition: 'A feeling of fellowship with others, as a result of sharing common attitudes, interests, and goals.',
    source: 'https://www.lexico.com/en/definition/community',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'cooperation',
    definition: 'The process of working together to the same end.',
    source: 'https://www.lexico.com/en/definition/cooperation',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'hope',
    definition: 'Expectation and desire for a certain thing to happen.',
    source: 'https://www.lexico.com/en/definition/hope',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'mourning',
    definition: 'To feel or express sorrow or grief.',
    source: 'https://www.dictionary.com/browse/mourn',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'play',
    definition: 'Engage in activity for enjoyment and recreation rather than a serious or practical purpose.',
    source: 'https://www.lexico.com/en/definition/play',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'safety',
    definition: 'The condition of being protected from or unlikely to cause danger, risk, or injury.',
    source: 'https://www.lexico.com/en/definition/safety',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'selfexpression',
    display: 'Self Expression',
    definition: 'The expression of one\'s feelings, thoughts, or ideas, especially in writing, art, music, or dance.',
    source: 'https://www.lexico.com/en/definition/self-expression',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'understanding',
    definition: 'Sympathetically aware of other people\'s feelings; tolerant and forgiving.',
    source: 'https://www.lexico.com/en/definition/understanding',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'acceptance',
    definition: 'The action or process of being received as adequate or suitable, typically to be admitted into a group.',
    source: 'https://www.lexico.com/en/definition/acceptance',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'beauty',
    definition: 'A combination of qualities, such as shape, color, or form, that pleases the aesthetic senses, especially the sight.',
    source: 'https://www.lexico.com/en/definition/beauty',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'belonging',
    definition: 'An affinity for a place or situation.',
    source: 'https://www.lexico.com/en/definition/belonging',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'challenge',
    definition: 'A difficult task, especially one that the person making the attempt finds more enjoyable because of that difficulty.',
    source: 'https://en.wiktionary.org/wiki/challenge',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'compassion',
    definition: 'Deep awareness of the suffering of another, coupled with the wish to relieve it.',
    source: 'https://en.wiktionary.org/wiki/compassion',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'competence',
    definition: 'The ability to do something successfully or efficiently.',
    source: 'https://www.lexico.com/en/definition/Competence',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'consideration',
    definition: 'A fact or a motive taken into account in deciding or judging something.',
    source: 'https://www.lexico.com/en/definition/consideration',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'contribution',
    definition: 'Something given or offered that adds to a larger whole.',
    source: 'https://en.wiktionary.org/wiki/contribution',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'creativity',
    definition: 'The ability to use imagination to produce a novel idea or product.',
    source: 'https://en.wiktionary.org/wiki/creativity',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'ease',
    definition: 'Absence of difficulty or effort.',
    source: 'https://www.lexico.com/en/definition/Absence',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'exercise',
    definition: 'A process or activity carried out for a specific purpose, especially one concerned with a specified area or skill.',
    source: 'https://www.lexico.com/en/definition/exercise',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'freedom',
    definition: 'The power or right to act, speak, or think as one wants without hindrance or restraint.',
    source: 'https://www.lexico.com/en/definition/freedom',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'learning',
    definition: 'The acquisition of knowledge or skills through experience, study, or by being taught.',
    source: 'https://www.lexico.com/en/definition/learning',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'mutuality',
    definition: 'The sharing of a feeling, action, or relationship between two or more parties.',
    source: 'https://www.lexico.com/en/definition/mutuality',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'order',
    definition: 'The arrangement or disposition of people or things in relation to each other according to a particular sequence, pattern, or method.',
    source: 'https://www.lexico.com/en/definition/order',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'peace',
    definition: 'Freedom from disturbance; tranquility.',
    source: 'https://www.lexico.com/en/definition/Freedom',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'respect',
    definition: 'Due regard for the feelings, wishes, rights, or traditions of others.',
    source: 'https://www.lexico.com/en/definition/respect',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'rest',
    definition: 'Freedom from activity or labor.',
    source: 'https://www.merriam-webster.com/dictionary/rest',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'tobeknown',
    display: 'To Be Known',
    definition: 'To Know and Be Known',
    source: '',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'tobeseen',
    display: 'To Be Seen',
    definition: 'To See and Be Seen',
    source: '',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'trust',
    definition: 'Confident expectation of something.',
    source: 'https://www.lexico.com/en/definition/trust',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'authenticity',
    definition: 'The quality of being real or true.',
    source: 'https://dictionary.cambridge.org/us/dictionary/english/authenticity',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'companionship',
    definition: 'Closeness with another person.',
    source: 'https://www.vocabulary.com/dictionary/companionship',
  },
  {
    type: CardType.Need,
    category: CardCategory.Meow,
    name: 'shared-reality',
    definition: 'Experiencing commonality with others\' inner states about the world.',
    source: 'https://pubmed.ncbi.nlm.nih.gov/26162223/',
  },
]
